<?php
$aryBodyId2Info=array(
		'1'=>array('eye','眼部整形'),
		'2'=>array('bosom','胸部整形'),
		'3'=>array('skin','皮肤美容'),
		'4'=>array('brow','眉部整形'),
		'5'=>array('jowl','颌面整形'),
		'6'=>array('belly','腰腹部整形'),
		'7'=>array('nose','鼻部整形'),
		'8'=>array('mouthlip','唇部整形'),
		'9'=>array('ear','耳部整形'),
		'10'=>array('hair','毛发整形'),
		'11'=>array('hip','臀部整形'),
		'12'=>array('genitalia','生殖整形'),
		'13'=>array('limb','四肢整形'),
		'14'=>array('dentist','口腔美容')
		);//整形部位的ID对应整形部位信息

$aryBodyUrl2Info=array(
		'all'=>array('所有部位',0),
		'eye'=>array('眼部整形',1),
		'bosom'=>array('胸部整形',2),
		'skin'=>array('皮肤美容',3),
		'brow'=>array('眉部整形',4),
		'jowl'=>array('颌面整形',5),
		'belly'=>array('腰腹部整形',6),
		'nose'=>array('鼻部整形',7),
		'mouthlip'=>array('唇部整形',8),
		'ear'=>array('耳部整形',9),
		'hair'=>array('毛发整形',10),
		'hip'=>array('臀部整形',11),
		'genitalia'=>array('生殖整形',12),
		'limb'=>array('四肢整形',13),
		'dentist'=>array('口腔美容',14)
		);//整形部位的英文字母对应整形部位信息

?>